server:
  port: 4005

spring:
  application:
    name: TOKEN-SERVICE-PRO1

eureka:
  client:
    register-with-client: true
    fetch-registry: true
    service-url:
      default:zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost